import Head from "next/head";
import Subscription from "@/components/general/Subscription";

export default function Blog() {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by Taodemy" />
      </Head>
      <main>
        <Subscription />
      </main>
    </>
  );
}
