import Head from "next/head";
import Subscription from "@/components/general/Subscription";
import BlogTitle from "@/components/general/BlogTitle";
import BlogGallery from "@/components/general/BlogGallery";

export default function Blog() {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by Taodemy" />
      </Head>
      <main>
        <BlogTitle />
        <BlogGallery />
        <Subscription />
      </main>
    </>
  );
}
