import Head from "next/head";
import Contact from "@/components/general/Contact";

export default function Blog() {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by Taodemy" />
      </Head>
      <main>
        <Contact />
      </main>
    </>
  );
}
