import Head from "next/head";
import ContactPage from "@/components/general/ContactPage";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by Taodemy" />
      </Head>
      <main>
        <ContactPage />
      </main>
    </>
  );
}
