import Contact from "@/components/general/Contact";
import Values from "@/components/general/OurValues";
import Head from "next/head";
import Hero from "@/components/general/Hero";
import Header from "@/layouts/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Taodemy Website</title>
        <meta name="description" content="Generated by Taodemy" />
      </Head>
      <main className="page__wrapper">
        <Header />
        <Hero />
        <Values />
        <Contact />
      </main>
    </>
  );
}
