import Head from "next/head";
import Hero from "@/components/general/Hero";
import WhatWeDo from "@/components/general/WhatWeDo";
import Contact from "@/components/general/Contact";
import Values from "@/components/general/OurValues";
import FeaturedWork from "../components/general/FeaturedWork";
import LatestNews from "@/components/general/LatestNews";
import Footer from "@/layouts/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Taodemy Website</title>
        <meta name="description" content="Generated by Taodemy" />
      </Head>
      <main>
        <Hero />
        <WhatWeDo />
        <Values />
        <FeaturedWork />
        <Contact />
        <LatestNews />
      </main>
    </>
  );
}
