import Head from "next/head";
import AboutUs from "@/components/general/AboutUs";
import OurValueV2 from "@/components/general/OurValue2";
import OurTeam from "@/components/general/OurTeam";
import Contact, { IContact } from "@/components/general/Contact";
import useMediaQuery from "@/hooks/useMediaQuery";
import EViewPortQuery from "@/constants/viewPortSize";
import { GetStaticProps } from "next";

export interface Props {
  IndexPage: IIndexPage;
}

export interface IIndexPage {
  Contact: IContact;
}

export interface PhoneSizeProp {
  isPhoneSize: boolean;
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const res = await fetch(`${process.env.WEBSITE_API_URL}/IndexPage`);
  const data: IIndexPage = await res.json();

  return {
    props: {
      IndexPage: data,
    },
  };
};

export default function Studio({ IndexPage }: Props) {
  const { PHONE } = EViewPortQuery;
  const isPhoneSize = useMediaQuery(PHONE);

  return (
    <>
      <Head>
        <title>Taodemy Website</title>
        <meta name="description" content="Generated by Taodemy" />
      </Head>
      <main>
        <AboutUs isPhoneSize={isPhoneSize} />
        <OurValueV2 isPhoneSize={isPhoneSize} />
        <OurTeam isPhoneSize={isPhoneSize} />
        <Contact {...IndexPage.Contact} />
      </main>
    </>
  );
}
