import Head from "next/head";
import AboutUs from "@/components/general/AboutUs";
import OurValueV2 from "@/components/general/OurValue2";
import OurTeam from "@/components/general/OurTeam";
import Contact from "@/components/general/Contact";
import useMediaQuery from "@/hooks/useMediaQuery";
import EViewPortQuery from "@/constants/viewPortSize";

export interface MatchesProp {
  matches: boolean;
}

export default function Studio() {
  const { PHONE } = EViewPortQuery;
  const matches = useMediaQuery(PHONE);

  return (
    <>
      <Head>
        <title>Taodemy Website</title>
        <meta name="description" content="Generated by Taodemy" />
      </Head>
      <main>
        <AboutUs matches={matches} />
        <OurValueV2 matches={matches} />
        <OurTeam matches={matches} />
        <Contact />
      </main>
    </>
  );
}
