#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#Check eslint standards
npm run lint || (

        echo '😤🏀👋😤 Eslint Check Failed. 😤🏀👋😤 
                Make the required changes listed above, add changes and try to commit again.
                You can read the ".turbo/turbo-eslint.log" of the failing project for more detail.
              '
        false; 
)

#Check pass all tests
npm run test || (
    
    echo '😤😂❌🤡 Test Failed. 😤😂❌🤡
            Make sure all tests pass and meet the required coverage threshold'
    false;
)